---
name: Lint Code Base

on:
  push:
    branches: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_GO: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          IGNORE_GENERATED_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
